[project]
name = "forensic-psych-report-drafter"
version = "0.1.0"
description = "An experimental forensic report drafter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.49.0",
    "langchain>=0.3.20",
    "langchain-text-splitters>=0.3.6",
    "pyqt6>=6.8.1",
]
